import type { Meta, StoryObj } from '@storybook/react';
import { CategoryRail } from '@/components/CategoryRail';
import { HomeHero } from '@/components/HomeHero';
import { HelpCenter } from '@/components/HelpCenter';
import { ContactForm } from '@/components/ContactForm';
import { DataTable } from '@/components/DataTable';
import { EditorialHero } from '@/components/EditorialHero';
import { ErrorPage } from '@/components/ErrorPage';
import { FeaturedStories } from '@/components/FeaturedStories';
import { InfoSplit } from '@/components/InfoSplit';
import { LinkColumns } from '@/components/LinkColumns';
import { NewsletterCallout } from '@/components/NewsletterCallout';
import { ImageCardGrid } from '@/components/ImageCardGrid';
import { ProductGrid } from '@/components/ProductGrid';
import { ProductDetail } from '@/components/ProductDetail';
import { ProductListing } from '@/components/ProductListing';
import { RepairBanner } from '@/components/RepairBanner';
import { SiteFooter } from '@/components/SiteFooter';
import { SiteNavigation } from '@/components/SiteNavigation';
import { ServiceHero } from '@/components/ServiceHero';
import { SearchPanel } from '@/components/SearchPanel';
import { StoreLocator } from '@/components/StoreLocator';
import { StepGrid } from '@/components/StepGrid';
import { StoryGrid } from '@/components/StoryGrid';
import { StoryDetail } from '@/components/StoryDetail';
import { TrustBar } from '@/components/TrustBar';
import { TextFeature } from '@/components/TextFeature';

const imageRoot = '/assets/ballard/images';
const meta = { title: 'Ballard/Components' } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

export const Navigation: Story = { render: () => <SiteNavigation brandHref="/" brandLabel="Ballard" brandLogo={`${imageRoot}/ballard-logo-black-transparent.svg`} utilityLinks={[{ id: 'repair', label: 'Repair', href: '#' }]} promo={{ id: 'promo', label: 'Free repair on any Ballard gear, any age', href: '#' }} navigation={[{ id: 'men', label: "Men's", href: '#' }, { id: 'women', label: "Women's", href: '#' }]} /> };
export const Hero: Story = { render: () => <HomeHero image={`${imageRoot}/photo-hero-deck-2.webp`} imageAlt="Rain gear on a wet deck" eyebrow="Back in stock" heading={'Fall\nfoul-weather gear'} description="The Salmon Bay Parka is back in slate. Heavy, and we repair it for free." primary={{ label: 'Shop rain gear', href: '#' }} secondary={[{ label: "Women's", href: '#' }, { label: "Men's", href: '#' }]} /> };
export const Categories: Story = { render: () => <CategoryRail items={[{ id: 'rain', image: `${imageRoot}/photo-hike-rain-3.webp`, imageAlt: 'Foul-weather gear', eyebrow: 'Shop', title: 'Foul-weather gear', href: '#', links: [{ label: "Men's", href: '#' }] }]} /> };
export const Products: Story = { render: () => <ProductGrid heading="Best sellers" allLabel="See all" allHref="#" products={[{ id: 'parka', image: `${imageRoot}/photo-kayak-0.webp`, imageAlt: 'Salmon Bay Parka', badge: 'Best seller', title: 'Salmon Bay Parka', href: '#', description: 'Standing on a wet deck for eight hours.', price: '$349', colors: ['#5d6b70', '#d4512c'] }]} /> };
export const Repair: Story = { render: () => <RepairBanner image={`${imageRoot}/photo-repair-2.webp`} imageAlt="Jacket repair" eyebrow="Repair" heading="Send it back. We'll fix it for free." description="Seams, zips, snaps, tape, and wax on any Ballard gear, any age." label="Start a repair" href="#" /> };
export const ImageCards: Story = { render: () => <ImageCardGrid heading="Shop by condition" variant="condition" cards={[{ id: 'deck', image: `${imageRoot}/photo-fishing-3.webp`, imageAlt: 'Deck work', eyebrow: 'By condition', title: 'Deck work', href: '#', links: [{ label: "Men's", href: '#' }] }]} /> };
export const Stories: Story = { render: () => <StoryGrid heading="Latest stories" allLabel="View all" allHref="#" stories={[{ id: 'story', image: `${imageRoot}/photo-utility-work-3.webp`, imageAlt: 'Line workers', title: 'How to build a winter uniform program that works', description: 'A practical operating guide for mapping conditions and fitting layers.', readTime: '8 min read', href: '#' }]} /> };
export const Trust: Story = { render: () => <TrustBar items={[{ id: 'since', heading: 'Since 1963', description: 'Started in Salmon Bay making foul-weather gear for the North Pacific fleet. Still do.' }]} /> };
export const Footer: Story = { render: () => <SiteFooter brandLogo={`${imageRoot}/ballard-logo-white-transparent.svg`} brandHref="/" brandName="Ballard" statement="Gear that earns its keep. Seattle, since 1963." newsletterLabel="Newsletter" newsletterDescription="Restocks, repair tips, and drops. About twice a month. No exclamation points." newsletterPlaceholder="Email" newsletterSubmitLabel="Sign up" newsletterSuccessMessage="You're on the list. First email goes out within two weeks." columns={[{ id: 'help', title: 'Help', links: [{ id: 'center', label: 'Help center', href: '#' }] }]} legalLinks={[{ id: 'privacy', label: 'Privacy notice', href: '#' }]} countryLabel="United States (USD)" copyright="© 2026 Ballard." /> };
export const Listing: Story = { render: () => <ProductListing breadcrumb={[{ label: 'Home', href: '#' }]} heading="Men's" description="Shells, waxed cotton, fleece, and work pants." categories={['All', 'Jackets and shells']} products={[{ id: 'parka', image: `${imageRoot}/photo-kayak-0.webp`, imageAlt: 'Salmon Bay Parka', title: 'Salmon Bay Parka', href: '#', description: 'Standing on a wet deck for eight hours.', price: '$349', colors: ['#5d6b70'] }]} /> };
export const Product: Story = { render: () => <ProductDetail breadcrumb={[{ label: 'Home', href: '#' }]} name="Salmon Bay Parka" tagline="Standing on a wet deck for eight hours." price="$349" colorName="Slate" colors={['#5d6b70']} sizes={['S', 'M', 'L']} gallery={[{ image: `${imageRoot}/photo-kayak-0.webp`, alt: 'Salmon Bay Parka' }]} delivery={[{ label: 'Delivery', value: 'Free shipping over $99.' }]} paragraphs={['Built for standing on a wet deck for eight hours.']} tradeoff="Heavy for its warmth." fit="Runs large through the shoulder." care="Machine wash cold." repairEligible specs={[{ label: 'Shell', value: '3-layer 70D nylon' }]} related={[]} /> };
export const ServicePageHero: Story = { render: () => <ServiceHero image={`${imageRoot}/photo-repair-7.webp`} imageAlt="Repair work" eyebrow="Repair" heading="Free repair. Any Ballard gear, any age." description="We've repaired gear since 1963." links={[{ label: 'Start a repair', href: '#', primary: true }]} /> };
export const Steps: Story = { render: () => <StepGrid heading="How it works" steps={[{ number: '1', title: "Tell us what's wrong", description: 'Describe the damage in a sentence.' }]} /> };
export const InformationSplit: Story = { render: () => <InfoSplit leftHeading="What we repair" rows={[{ label: 'Shells and parkas', value: 'Seam tape, zips, cuffs' }]} rightSections={[{ heading: "What we don't", paragraphs: ['Socks, gloves, and boots.'] }]} /> };
export const Form: Story = { render: () => <ContactForm heading="Start a repair" description="Fill this in and we'll email a label." kind="repair" /> };
export const Help: Story = { render: () => <HelpCenter heading="Help center" introduction="Short answers." faqGroups={[{ heading: 'Orders and shipping', questions: [{ title: 'When will my order ship', answer: 'In-stock gear ships in 1 to 2 business days.' }] }]} sizes={[{ size: 'M', chest: '38 to 40', waist: '32 to 34' }]} info={[{ heading: 'Account', text: 'Everything works without one.' }]} /> };
export const Editorial: Story = { render: () => <EditorialHero image={`${imageRoot}/photo-coast-pnw-0.webp`} imageAlt="Foggy coast" titleLead="Ballard" titleTail="stories" /> };
export const TextAndFacts: Story = { render: () => <TextFeature paragraphs={['Gear that earns its keep.']} facts={[{ label: 'Founded', value: '1963, Seattle' }]} /> };
export const Table: Story = { render: () => <DataTable heading="Timeline" theme="paper" columns={['Year', 'Event']} rows={[{ id: '1963', cells: ['1963', 'Ballard opens in Salmon Bay.'] }]} /> };
export const Columns: Story = { render: () => <LinkColumns variant="cards" items={[{ id: 'careers', heading: 'Careers', description: 'Seattle, the stores, and the repair shop.', label: 'Open roles', href: '#' }]} /> };
export const Featured: Story = { render: () => <FeaturedStories heading="Some favorites" stories={[{ id: 'repair', category: 'Repair', title: 'How to reproof waxed cotton', readTime: '4 min read', href: '#', image: `${imageRoot}/photo-repair-3.webp`, imageAlt: 'Repair' }]} /> };
export const NewsletterCard: Story = { render: () => <NewsletterCallout heading="Hear about the next drop" description="About twice a month." label="Newsletter" formDescription="Restocks, repair tips, and drops." /> };
export const Locator: Story = { render: () => <StoreLocator heading="Find a store" description="Every store takes repairs." image={`${imageRoot}/photo-store-1.webp`} imageAlt="Store" stores={[{ id: 'fremont', name: 'Ballard Fremont', address: '3410 Fremont Ave N, Seattle, WA 98103', hours: 'Mon to Sat 10 to 7', services: ['Repair'] }]} /> };
export const Search: Story = { render: () => <SearchPanel description="Try a condition, a material, or a model name." suggestions={['rain', 'waxed cotton']} /> };
export const Article: Story = { render: () => <StoryDetail kind="Repair" title="How to reproof waxed cotton" description="Once a year, 40 minutes, a hair dryer." author="Ballard repair" date="August 12, 2026" readTime="4 min read" image={`${imageRoot}/photo-repair-3.webp`} imageAlt="Repairing waxed cotton" paragraphs={['Waxed cotton sheds water because the fibers are coated.']} more={[]} /> };
export const NotFound: Story = { render: () => <ErrorPage code="404" heading="That page isn't here." description="The link is wrong or the gear sold out. Drops do that." links={[{ id: 'home', label: 'Home', href: '#', variant: 'primary' }, { id: 'shop-mens', label: "Shop men's", href: '#', variant: 'outline' }]} /> };
