'use client';
/* eslint-disable @next/next/no-html-link-for-pages, aci-rules/no-raw-tailwind-values */

/* eslint-disable @next/next/no-img-element */
import { useId, useState, type ReactNode } from 'react';
import type { ContentProps } from '@/cms/contracts/components/productDetail.contract';
import { CommerceProductCard } from './CommerceProductCard';
import { useCart } from './cart/CartProvider';

function priceNumber(price: string) { return Number(price.replace(/[^0-9.]/g, '')); }
function productSlug(breadcrumb: ContentProps['breadcrumb'], fallback: string) { return breadcrumb.at(-1)?.href.split('/').filter(Boolean).at(-1) ?? fallback.toLowerCase().replace(/[^a-z0-9]+/g, '-'); }
function Chevron({ open }: { open: boolean }) { return <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true" className={`shrink-0 transition-transform ${open ? 'rotate-180' : ''}`}><path d="M2 5l5 5 5-5" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg>; }
function Accordion({ title, children, defaultOpen = false }: { title: string; children: ReactNode; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen); const id = useId();
  return <div className="border-b hairline"><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpen((value) => !value)} className="flex w-full items-center justify-between gap-4 py-4 text-left text-[length:var(--text-15)] font-medium"><span>{title}</span><Chevron open={open} /></button>{open && <div id={id} className="pb-4 text-sm leading-relaxed text-ink-2">{children}</div>}</div>;
}

function BuyPanel({ id, name, price, colorName, colors, colorOptions, sizes, galleryImage, delivery }: Pick<ContentProps, 'name' | 'price' | 'colorName' | 'colors' | 'colorOptions' | 'sizes' | 'delivery'> & { id: string; galleryImage: string }) {
  const options = colorOptions ?? colors.map((hex, index) => ({ hex, name: index === 0 ? colorName : `Color ${index + 1}` }));
  const [color, setColor] = useState(options[0]);
  const [size, setSize] = useState<string | null>(sizes.length === 1 ? sizes[0] : null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<'new' | 'repaired'>('new');
  const { add } = useCart();
  return <div className="rounded-lg border hairline bg-white">
    <div className="grid grid-cols-2 border-b hairline text-sm" role="tablist" aria-label="Condition">{(['new', 'repaired'] as const).map((condition) => <button key={condition} type="button" role="tab" aria-selected={tab === condition} onClick={() => setTab(condition)} className={`flex items-center justify-center gap-2 py-3 ${tab === condition ? 'bg-white font-semibold' : 'bg-paper text-ink-2'} ${condition === 'new' ? 'rounded-tl-lg' : 'rounded-tr-lg'}`}><span className={`h-3 w-3 rounded-full border ${tab === condition ? 'border-ink bg-ink' : 'border-line'}`} aria-hidden="true" />{condition === 'new' ? 'Shop new' : 'Shop repaired'}</button>)}</div>
    {tab === 'repaired' ? <div className="p-5 text-sm text-ink-2"><p>Repaired {name}s come from returns and repair stock. Inspected, fixed, and sold at 40% off. Stock changes daily.</p><p className="mt-3">None in stock right now. <a href="/repair" className="underline underline-offset-4">How repair works</a></p></div> : <div className="p-5"><div><p className="text-sm"><span className="font-medium">Color</span> <span className="text-ink-2">{color.name}</span></p><div className="mt-2 flex gap-2">{options.map((option) => <button key={`${option.name}-${option.hex}`} type="button" aria-label={option.name} aria-pressed={color.name === option.name} onClick={() => setColor(option)} className={`h-8 w-8 rounded-full ring-offset-2 transition ${color.name === option.name ? 'ring-2 ring-ink' : 'ring-1 ring-black/15 hover:ring-ink'}`} style={{ backgroundColor: option.hex }} />)}</div></div>
      <div className="mt-5"><div className="flex items-center justify-between text-sm"><span className="font-medium">Size{size && <span className="ml-1 font-normal text-ink-2">{size}</span>}</span><a href="/help#sizing" className="text-xs underline underline-offset-4">Size guide</a></div><div className="mt-2 grid grid-cols-4 gap-2" role="radiogroup" aria-label="Size">{sizes.map((option) => <button key={option} type="button" role="radio" aria-checked={size === option} onClick={() => { setSize(option); setError(null); }} className={`h-10 rounded-md border text-sm transition ${size === option ? 'border-ink bg-ink text-white' : 'border-line bg-paper hover:border-ink'}`}>{option}</button>)}</div>{error && <p className="mt-2 text-xs text-red-700" role="alert">{error}</p>}</div>
      <div className="mt-5 flex gap-2"><button type="button" aria-label="Save for later" className="btn btn-outline h-12 w-12 shrink-0 rounded-full px-0"><svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M12 20s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 10c0 5.5-7 10-7 10z" /></svg></button><button type="button" onClick={() => { if (!size) { setError('Pick a size first.'); return; } add({ slug: id, name, price: priceNumber(price), color: color.name, size, image: galleryImage }); }} className="btn btn-primary h-12 flex-1 text-[length:var(--text-15)]">Add to bag · {price}</button></div>
      <dl className="mt-5 space-y-2 border-t hairline pt-4 text-sm">{delivery.map((item) => <div key={item.label} className="flex gap-3"><dt className="w-28 shrink-0 text-ink-3">{item.label}</dt><dd>{item.value}{item.label === 'Store pickup' && <a href="/stores" className="ml-1 underline underline-offset-4">Change store</a>}</dd></div>)}</dl>
    </div>}
  </div>;
}

export function ProductDetail({ breadcrumb, name, tagline, price, colorName, colors, colorOptions, sizes, made, gallery, delivery, paragraphs, tradeoff, fit, care, repairEligible, specs, related }: ContentProps) {
  return <div className="container-x pb-16 pt-5">
    <nav className="text-xs text-ink-2" aria-label="Breadcrumb">{breadcrumb.map((item, index) => <span key={`${item.href}-${item.label}`}>{index > 0 && <span className="mr-[18px]" aria-hidden="true">›</span>}<a href={item.href}>{item.label}</a></span>)}</nav>
    <div className="mt-5 grid gap-8 lg:grid-cols-[minmax(0,1.35fr)_minmax(360px,1fr)] lg:gap-12"><div className="grid grid-cols-2 content-start gap-3">{gallery.map((item, index) => <div key={item.image} className={`relative overflow-hidden rounded-lg bg-paper-2 ${index === 0 ? 'col-span-2 aspect-[4/3] md:col-span-1 md:aspect-[4/5]' : 'aspect-[4/5]'}`}><img src={item.image} alt={item.alt} className="h-full w-full object-cover" />{item.caption && <span className="absolute bottom-3 left-3 rounded-full bg-white/90 px-2.5 py-1 text-[length:var(--text-11)] font-medium">{item.caption}</span>}</div>)}</div>
      <div className="lg:sticky lg:top-6 lg:self-start"><h1 className="text-3xl font-semibold tracking-tight md:text-[32px]">{name}</h1><p className="mt-1.5 text-[length:var(--text-15)] text-ink-2">{tagline}</p>{made && <p className="mt-2 text-sm font-medium">{made} made. Numbered.</p>}<div className="mt-5"><BuyPanel id={productSlug(breadcrumb, name)} name={name} price={price} colorName={colorName} colors={colors} colorOptions={colorOptions} sizes={sizes} galleryImage={gallery[0]?.image ?? ''} delivery={delivery} /></div><div className="mt-8 space-y-4 text-[length:var(--text-15)] leading-relaxed text-ink-2">{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-6 rounded-lg bg-paper px-5 py-4"><p className="text-xs font-semibold uppercase tracking-wider text-ink-3">The tradeoff</p><p className="mt-1 text-[length:var(--text-15)]">{tradeoff}</p></div><div className="mt-6">{fit && <Accordion title="Fit" defaultOpen><p>{fit}</p></Accordion>}<Accordion title="Specs and materials" defaultOpen><table className="w-full text-sm"><tbody>{specs.map((spec) => <tr key={spec.label} className="border-t hairline first:border-t-0"><th scope="row" className="w-36 py-2 pr-3 text-left font-medium text-ink-3">{spec.label}</th><td className="py-2">{spec.value}</td></tr>)}</tbody></table></Accordion><Accordion title="Care and repair">{care && <p>{care}</p>}{repairEligible ? <p className="mt-2">Repair-eligible. Free for the life of the gear. <a href="/repair" className="underline underline-offset-4">Start a repair</a></p> : <p className="mt-2">Not repair-eligible. When it wears out, it&apos;s worn out.</p>}</Accordion><Accordion title="Shipping and returns"><p>Free shipping on orders over $99. 60-day returns, worn or not. Exchanges by mail or at any store.</p></Accordion></div></div>
    </div>
    {related.length > 0 && <section className="mt-16 border-t hairline pt-10"><h2 className="text-2xl font-semibold tracking-tight">Goes with it</h2><div className="mt-6 grid grid-cols-2 gap-x-4 gap-y-8 lg:grid-cols-4">{related.map((product) => <CommerceProductCard key={product.id} product={product} />)}</div></section>}
  </div>;
}
